name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macos-11]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.0
        env:
          CIBW_PLATFORM: linux
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BEFORE_BUILD: python -m pip install wheel "conan==1.59.0" pytest datashader holoviews pytest-xdist -U pip && python conanfile.py && python build_wheel.py
          CIBW_CONFIG_SETTINGS: "-w /tmp"
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          